name: "CI"

on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile
      - README.md
      - docs/**
      - pyproject.toml
      - scripts/**
      - .*
  workflow_dispatch:

jobs:
  validate:
    name: Run linters and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run linters
        uses: astral-sh/ruff-action@v3

      # - name: Run unit tests
      #  run: |
      #    PYTHONPATH=src uv run -- pytest
      #     . ./.venv/bin/activate
      #     export DB_URI=instance/test.sqlite3
      #     PYTHONPATH=src pytest

  build:
    name: Build project
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for semver

      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
